### ISSUE TITLE
Navigation tab too tall

### ISSUE THREAD

**Issue by DChambersSTFC** [OpticalShadows/ACleanModernUI#12]
Latest update seems to have affected the styling for the navigation ribbon, making it too long. Right-clicking on a scene requires you to scroll down in the tab to see the options.

Examples:
![image](https://user-images.githubusercontent.com/14294209/112770216-8bde8700-901d-11eb-8957-bb15289478e9.png)
![image](https://user-images.githubusercontent.com/14294209/112770223-91d46800-901d-11eb-95cd-6104358dfec2.png)

**Comment by OpticalShadows** [comment]
Fixed in the latest update!
