### ISSUE TITLE
[Bug?] Scene list too big?

### ISSUE THREAD

**Issue by PalaNolho** [OpticalShadows/ACleanModernUI#14]
Not sure if it's a bug or intentional, but the Scene selection is way too big and it's always collapsed. 
Actually, the toolbar buttons seem also way too big

It would be also great to choose if the hotbar is pinned on left, center or right

![image](https://user-images.githubusercontent.com/6009914/116085506-caa44300-a696-11eb-84cc-c7779150992b.png)

**Comment by OpticalShadows** [comment]
Hello,

This is the way it is supposed to look however it's probably my least favorite part of the UI. It was a work in progress to try and mimic the roll 20 scene browser but it would require more coding to get it the way I would like. Ideally it would be a scrollable list of cards that doesn't take up as much screen real-estate but it creates problems with the right click menu when I build it that way. It's still a WIP

**Comment by miguel-pinto-prodmad** [comment]
OK. I think there are some modules/themes that already handle that.
Maybe you will find some inspiration in them.

**Comment by OpticalShadows** [comment]
I pushed a small update that reverts it back to the default styling until I have a system in place for what I am going for.
