### ISSUE TITLE
Other visual issues

### ISSUE THREAD

**Issue by WyntherKnight** [OpticalShadows/ACleanModernUI#2]
Hello again.

When you right click the token, the icons are dark.  
Status effects are barely visible on the combat tracker.

![issue2](https://user-images.githubusercontent.com/66346903/111558361-98ffa880-87c9-11eb-88ed-99f341593f5a.jpg)
![issue3](https://user-images.githubusercontent.com/66346903/111558365-9c932f80-87c9-11eb-99ad-8e0c00a9f980.jpg)

**Comment by OpticalShadows** [comment]
HI! Could you list what other modules you are running? I want to track down what is overwriting my settings. In a fresh game, it should be like this image:
![image](https://user-images.githubusercontent.com/8631043/111561480-e4cf3500-876a-11eb-9383-5926080b35e5.png)

I did notice the effects in the tracker and will push a fix for that as well.

**Comment by WyntherKnight** [comment]
Thanks for the idea, I did a test and saw that one module was interfering with it, Illamdril's Token HUD Scaler. They just make the status effects bigger on the token so I can just forgo that. I removed the module and the token icons are now readable.

**Comment by OpticalShadows** [comment]
Sorry for the late update but just pushed a fix that should resolve this issue with the module.

**Comment by WyntherKnight** [comment]
Thanks! If any more issues come up, I'll let you know.
