### ISSUE TITLE
Dull colors with another module

### ISSUE THREAD

**Issue by WyntherKnight** [OpticalShadows/ACleanModernUI#8]
Hello again.

The colors of  the icons on the "Custom Hotbar" module becomes dull.

Without A Clean Modern UI Module
![without](https://user-images.githubusercontent.com/66346903/111953051-09d3f700-8b21-11eb-8fd3-57d923aa81d0.jpg)

With A Clean Modern UI Module
![with](https://user-images.githubusercontent.com/66346903/111953103-1e17f400-8b21-11eb-8d76-5fbc791ea7ae.jpg)

**Comment by OpticalShadows** [comment]
Hi, yes this is a byproduct of trying to incorporate custom hotbar coloring into my UI without overdoing the colors. It can easily be reverted but I'll look into a way of keeping the effect on the empty macros and remove it from ones with images in them

**Comment by WyntherKnight** [comment]
Thanks so much for looking into this.
